name: Python Tests

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flask flask-cors apscheduler
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      - name: Run tests
        working-directory: ./backend
        run: |
          pytest --cov --cov-report=xml

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jinish08/Auction-Sphere-3
          
      - name: Tests Status
        if: ${{ always() }}
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "All tests passed successfully!"
          else
            echo "Tests failed. Check the logs for details."
            exit 1
          fi