name: React Tests

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run Jest Tests
        run: npm test
        
      - name: Tests Status
        if: ${{ always() }}
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "All tests passed successfully!"
          else
            echo "Tests failed. Check the logs for details."
            exit 1
          fi